"""instututuion update

Revision ID: 08188dab0232
Revises: 
Create Date: 2023-03-28 06:25:43.769569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08188dab0232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('institution')

    # ### end Alembic commands ###
