"""posts model

Revision ID: 187619f6c67e
Revises: 08188dab0232
Create Date: 2023-04-05 21:46:42.804224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '187619f6c67e'
down_revision = '08188dab0232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_publish_date'), ['publish_date'], unique=False)
        batch_op.drop_column('text')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('text', mysql.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_post_publish_date'))
        batch_op.drop_column('body')

    # ### end Alembic commands ###
