"""posts model add

Revision ID: d41e3f13deea
Revises: 187619f6c67e
Create Date: 2023-04-05 23:16:09.742089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd41e3f13deea'
down_revision = '187619f6c67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', mysql.TEXT(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
